name: Main workflow

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  plugin_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Test plugin (OAuth Token)
        uses: asdf-vm/actions/plugin-test@v1
        env:
          OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: kustomize version
      - name: Test plugin (GitHub API Token)
        uses: asdf-vm/actions/plugin-test@v1
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: kustomize version

